[versions]
agp           = "8.5.2"
kotlin        = "2.0.0"
ksp           = "2.0.0-1.0.22"
hilt          = "2.51.1"
hiltNav       = "1.2.0"
composeBom    = "2024.09.02"
navigation    = "2.8.1"
lifecycle     = "2.8.5"
activity      = "1.9.2"
coreKtx       = "1.13.1"
datastore     = "1.1.1"
okhttp        = "4.12.0"
coroutines    = "1.8.1"
serialization = "1.7.3"
coil          = "2.7.0"
browser       = "1.8.0"

[libraries]
compose-bom              = { module = "androidx.compose:compose-bom",                       version.ref = "composeBom" }
compose-ui               = { module = "androidx.compose.ui:ui" }
compose-ui-graphics      = { module = "androidx.compose.ui:ui-graphics" }
compose-ui-tooling       = { module = "androidx.compose.ui:ui-tooling" }
compose-ui-preview       = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-ui-fonts         = { module = "androidx.compose.ui:ui-text-google-fonts" }
material3                = { module = "androidx.compose.material3:material3" }
material-icons           = { module = "androidx.compose.material:material-icons-extended" }
core-ktx                 = { module = "androidx.core:core-ktx",                            version.ref = "coreKtx" }
activity-compose         = { module = "androidx.activity:activity-compose",                version.ref = "activity" }
lifecycle-runtime        = { module = "androidx.lifecycle:lifecycle-runtime-ktx",          version.ref = "lifecycle" }
lifecycle-viewmodel      = { module = "androidx.lifecycle:lifecycle-viewmodel-compose",    version.ref = "lifecycle" }
navigation-compose       = { module = "androidx.navigation:navigation-compose",            version.ref = "navigation" }
browser                  = { module = "androidx.browser:browser",                          version.ref = "browser" }
hilt-android             = { module = "com.google.dagger:hilt-android",                   version.ref = "hilt" }
hilt-compiler            = { module = "com.google.dagger:hilt-android-compiler",          version.ref = "hilt" }
hilt-nav                 = { module = "androidx.hilt:hilt-navigation-compose",            version.ref = "hiltNav" }
okhttp                   = { module = "com.squareup.okhttp3:okhttp",                      version.ref = "okhttp" }
okhttp-log               = { module = "com.squareup.okhttp3:logging-interceptor",         version.ref = "okhttp" }
serialization-json       = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
datastore                = { module = "androidx.datastore:datastore-preferences",         version.ref = "datastore" }
coroutines               = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
coil                     = { module = "io.coil-kt:coil-compose",                          version.ref = "coil" }
android-mail             = { module = "com.sun.mail:android-mail",        version = "1.6.7" }
android-activation       = { module = "com.sun.mail:android-activation",  version = "1.6.7" }

[plugins]
android-app    = { id = "com.android.application",             version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android",        version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serial  = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
hilt           = { id = "com.google.dagger.hilt.android",      version.ref = "hilt" }
ksp            = { id = "com.google.devtools.ksp",             version.ref = "ksp" }
